apiVersion: v1
kind: Pod
metadata:
  name: demo-3
spec:
  containers:
    - name: nginx
      image: nginx:1.24.0-alpine3.17
      ports:
        - containerPort: 80
      volumeMounts:
        - name: app-config-volume #volume's name, defined below
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config #app-config - 前面先建好的 configmap name