apiVersion: v1
kind: Pod
metadata:
  name: demo-2
spec:
  containers:
    - name: nginx
      image: nginx:1.24.0-alpine3.17
      ports:
        - containerPort: 80
      env:
        - name: APP_COLOR_NEW
          valueFrom:
            configMapKeyRef:
              name: app-config #configMap name
              key: APP_COLOR #這邊的 key 要是 ConfigMap 裡面使用的 key name
