apiVersion: v1
kind: Pod
metadata:
  name: demo-1
spec:
  containers:
    - name: nginx
      image: nginx:1.24.0-alpine3.17
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: app-config #app-config - 前面先建好的 configmap name