apiVersion: v1
kind: Service
metadata:
  namespace: ironman
  name: db-service
  labels:
    name: db-service
    app: prac-node-login
spec:
  # type: ClusterIP
  selector: # map the pod label
    name: db-pod
    app: prac-node-login
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
