apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rolling
  annotations:
    kubernetes.io/change-cause: "change version to nginx:1.24"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2       
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.24