apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  containers:
    - name: container1
      image: chihhuiw/nodejs-helloworld:1.0.0
      imagePullPolicy: Always # 預設是 IfNotPresented
      command: ["node", "/app/index.js"]
      args: ["3001"]
      ports:
        - containerPort: 3001
      volumeMounts:
        - mountPath: /demo1
          name: demo-volume
    - name: container2
      image: chihhuiw/nodejs-helloworld:1.0.0
      imagePullPolicy: Always
      command: ["node", "/app/index.js"]
      args: ["3002"]
      ports:
        - containerPort: 3002
      volumeMounts:
        - mountPath: /demo2
          name: demo-volume
  volumes:
    - name: demo-volume
      emptyDir: {}