apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-utilization
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: php-apache # will find Deployment and its name is php-apache
  minReplicas: 2  # auto hpa from 2-10
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60